### PR TITLE
Makes it compatible with Python 3.7 and below

### PR DESCRIPTION
**Pull request by Arubinu**
Hello,

I propose these corrections to make compatible Jean-Paul Start with the latest versions of Python (Python3.7) and PySide (PySide2).

There were different types of corrections:
  - Problems of internal imports to the project,
  - Change the exception syntax,
  - some type changes,
  - The term "async" which is now reserved.

### CODE REVIEW

**Comment by MrFrangipane** [comment]
Hello,

Thank you very much for your interest in our projet, and for your contribution proposal !

All the changes you made seem quite okay with me, except the part where you changed `async` :

- I think that the policy for reserved keywords in python is to append an underscore at the end of the word. That would change arguments to `async_` not `async_on`
- Config files (batches) should not be affected by your change, the word `async` is not reserved in YAML :)

What do you think of those remarks ?

**Comment by Arubinu** [comment]
Hello :)

I agree, I chose ***_on*** because I did not know what else to put, and yes normally it does not affect the key YAML side.

So, I have to change all my ```async_on``` by ```async_``` (nothing else to change if I understand correctly)?

And no worries for adjustments, it's a good application ;)

**Comment by MrFrangipane** [comment]
Sorry for the late reply !

Thank you for the changes you kindly made according to my remarks :)

Since the API is not broken, maybe we could consider this a feature ?
If so, the version should be bumped to 2.3.0

Thanks again for your contribution

**Comment by Arubinu** [comment]
No problem.

I'm glad these changes are useful :)

**Pull request merged**
